
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Merge
{

using System;
    using System.Collections.Generic;
    
public partial class Teaching_Stuff
{

    public string ID { get; set; }

    public int Course_id { get; set; }

    public string Office { get; set; }

    public string Reception_day { get; set; }

    public Nullable<double> Reception_startTime { get; set; }

    public Nullable<double> Reception_endTime { get; set; }

}

}
