//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Courses
    {
        public string student_id { get; set; }
        public string course_id { get; set; }
        public Nullable<int> grade_a { get; set; }
        public Nullable<int> grade_b { get; set; }
        public Nullable<int> grade_c { get; set; }
        public Nullable<int> quiz1 { get; set; }
        public Nullable<int> quiz2 { get; set; }
        public Nullable<int> final_grade { get; set; }
    }
}
